# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Expose port 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: myuser@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5000:80' # Expose port 80 for pgAdmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres:
  pgadmin_data:
  redis_data:
